import React,{useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{Users,CalendarDays,FileText,ShieldAlert,Plus,Search,ClipboardList,HeartHandshake,Activity,Save,Trash2,ChevronLeft,Printer,Download,LayoutDashboard,Target,Brain,CheckCircle2}from'lucide-react';import'./style.css';
const forms={
'entrevista':{title:'Entrevista inicial',sections:[['Datos personales',['Nombre y apellido','Edad / Fecha de nacimiento','Ocupación / Estudios','Estado civil / Convivencia','Teléfono','Email']],['Motivo de consulta',['¿Qué te hizo buscar terapia ahora?','¿Qué está pasando actualmente que te preocupa / duele / desborda?','¿Desde cuándo te pasa?','¿Qué intentaste hacer hasta ahora para manejarlo?','¿Qué esperás del proceso terapéutico?']],['Historia del problema actual',['¿Cómo comenzó? (evento, etapa, situación desencadenante)','¿Con qué frecuencia ocurre?','¿Qué pensamientos aparecen en esos momentos?','¿Qué emociones predominan?','¿Qué señales físicas aparecen?','¿Qué conductas realizás ante eso?']]]},
'historia':{title:'Historia clínica',sections:[['Información del paciente',['DNI','Fecha de nacimiento','Género','Edad','Domicilio','Estado civil','Ocupación','Teléfono / móvil']],['Motivo de consulta',['Motivo aparente','Derivación / profesional que deriva','Historia y evolución','Antecedentes relevantes','Red de apoyo / recursos']]]},
'objetivos':{title:'Objetivos terapéuticos',sections:[['Admisión',['DNI','Fecha de admisión','Motivo de consulta','Problema presentado (en palabras del paciente)','¿Qué espera de la terapia?']],['Metas iniciales',['Objetivos que desea lograr','Cambios que desea conseguir','Indicadores de avance']]]},
'analisis':{title:'Análisis funcional',sections:[['Análisis ABC',['Antecedentes: factores situacionales, sociales y emocionales','Conducta: ¿cuál es la conducta que genera problemas?','Consecuencias: ¿qué ocurrió, qué hace, qué siente, qué ocasiona?']]]},
'tratamiento':{title:'Plan de tratamiento',sections:[['Diagnóstico y formulación',['Diagnóstico presuntivo / CIE-10','Formulación del caso']],['Enfoque terapéutico',['Enfoques seleccionados (TCC, Sistémico, Psicodinámico, Humanista/Gestalt, EMDR, ACT u otro)','Técnicas y estrategias planificadas']],['Encuadre',['Frecuencia de sesiones','Duración estimada','Modalidad presencial/online','Duración de cada sesión']],['Objetivos profesionales',['Corto plazo','Mediano plazo','Largo plazo']]]},
'seguimiento':{title:'Seguimiento de sesión',sections:[['Sesión',['Fecha','Número de sesión','Cambios / estado de ánimo / situaciones de la semana','Resumen de lo trabajado / técnica o actividad utilizada','Tarea terapéutica proporcionada','Observaciones y próximos pasos']]]},
'riesgo':{title:'Evaluación inicial de riesgo',sections:[['Riesgo suicida',['¿Pensamientos de hacerse daño o morir?','¿Plan?','¿Medidas preparatorias?','¿Intentos previos?','¿Acceso a medios letales?','¿Red de apoyo?','Nivel de riesgo: bajo / moderado / alto','Observaciones']],['Riesgo heteroagresivo',['Pensamientos de hacer daño a otros','Plan o intención','Persona específica identificada','Antecedentes de conductas agresivas']],['Factores y acción',['Consumo de sustancias / psicofármacos sin prescripción','Factores protectores','Factores de riesgo','Conclusión y plan de acción inmediato','¿Se requiere derivación urgente?']]]},
'seguridad':{title:'Plan de seguridad',sections:[['Plan',['Señales de alerta personales','Estrategias propias de afrontamiento','Personas de apoyo (nombre, vínculo, teléfono)','Profesional tratante y servicios de emergencia','Compromisos de seguridad','Fecha de elaboración']]]},
'consentimiento':{title:'Consentimiento informado',sections:[['Tratamiento',['Tipo: adulto / menor','DNI paciente / responsable','Características y enfoque del tratamiento','Duración','Frecuencia','Días','Honorarios','Modalidad']],['Derechos, obligaciones y confidencialidad',['Información y derechos comunicados','Política de cancelación / asistencia','Confidencialidad y excepciones','Nombre y DNI de quien consiente','Fecha / constancia de firma']]]},
'informes':{title:'Informes, derivación y alta',sections:[['Informe para terceros',['Destinatario / institución','Motivo de consulta y diagnóstico presuntivo','Descripción del tratamiento','Evolución y estado actual','Observaciones relevantes']],['Derivación',['Profesional receptor / especialidad','Motivo de derivación','Resumen clínico','Diagnóstico presuntivo / CIE-10','Medicación actual','Nivel de urgencia']],['Alta terapéutica',['Fecha de inicio / cierre','Total de sesiones','Motivo original','Diagnóstico presuntivo / CIE-10','Tipo de cierre','Resumen del proceso','Logros y cambios observados','Objetivos alcanzados']]]}}
const docList=[['entrevista','Entrevista inicial'],['historia','Historia clínica'],['objetivos','Objetivos terapéuticos'],['analisis','Análisis funcional'],['tratamiento','Plan de tratamiento'],['seguimiento','Seguimiento de sesiones'],['riesgo','Evaluación inicial de riesgo'],['seguridad','Plan de seguridad'],['consentimiento','Consentimiento informado'],['informes','Informes y derivación']];
const load=()=>JSON.parse(localStorage.getItem('cp_data')||'{"patients":[],"records":{},"appointments":[]}');
function App(){const[data,setData]=useState(load);const[view,setView]=useState('dashboard');const[selected,setSelected]=useState(null);const[form,setForm]=useState(null);const[q,setQ]=useState('');const persist=n=>{setData(n);localStorage.setItem('cp_data',JSON.stringify(n))};const patient=data.patients.find(p=>p.id===selected);const addPatient=()=>{const name=prompt('Nombre completo del paciente');if(!name?.trim())return;const p={id:String(Date.now()),name:name.trim(),dni:'',phone:'',email:'',admission:new Date().toISOString().slice(0,10)};persist({...data,patients:[...data.patients,p]});setSelected(p.id);setView('patient')};const removePatient=id=>{if(!confirm('¿Eliminar este paciente y sus registros locales?'))return;const r={...data.records};delete r[id];persist({...data,patients:data.patients.filter(p=>p.id!==id),records:r});setView('patients');setSelected(null)};const updatePatient=(k,v)=>persist({...data,patients:data.patients.map(p=>p.id===selected?{...p,[k]:v}:p)});const record=(data.records[selected]||{})[form]||{};const saveField=(key,val)=>{const records={...data.records,[selected]:{...(data.records[selected]||{}),[form]:{...record,[key]:val,_updated:new Date().toISOString()}}};persist({...data,records})};const stats=useMemo(()=>({patients:data.patients.length,records:Object.values(data.records).reduce((a,x)=>a+Object.keys(x).length,0)}),[data]);
const Side=()=> <aside><div className="brand"><img src="/psicovida-isotipo.png" alt="PsicoVida Consultorio Psicológico"/><div className="brandText"><strong>PsicoVida</strong><small>Consultorio Psicológico</small></div></div><nav><button onClick={()=>setView('dashboard')}><LayoutDashboard/>Panel</button><button onClick={()=>setView('patients')}><Users/>Pacientes</button><button onClick={()=>setView('agenda')}><CalendarDays/>Agenda</button><button onClick={()=>setView('documents')}><FileText/>Documentos</button><button onClick={()=>setView('risk')}><ShieldAlert/>Riesgo y seguridad</button></nav><div className="privacy">🔒 Entorno clínico privado · PsicoVida</div></aside>;
const Dashboard=()=> <><header><div><p>Centro Psicológico PsicoVida</p><h1>Panel clínico</h1></div><button className="primary" onClick={addPatient}><Plus/> Nuevo paciente</button></header><section className="stats"><article><Users/><div><strong>{stats.patients}</strong><span>Pacientes</span></div></article><article><ClipboardList/><div><strong>{stats.records}</strong><span>Registros guardados</span></div></article><article><FileText/><div><strong>{docList.length}</strong><span>Módulos clínicos</span></div></article></section><section className="panel"><h2>Accesos rápidos</h2><div className="quick">{docList.slice(0,6).map(([id,n])=><button key={id} onClick={()=>setView('patients')}><FileText/><b>{n}</b><span>Abrir desde expediente</span></button>)}</div></section></>;
const Patients=()=> <><header><div><p>Gestión clínica</p><h1>Pacientes</h1></div><button className="primary" onClick={addPatient}><Plus/>Registrar paciente</button></header><section className="panel"><div className="title"><h2>Directorio</h2><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar paciente"/></div></div>{data.patients.filter(p=>p.name.toLowerCase().includes(q.toLowerCase())).map(p=><div className="patient" key={p.id}><div className="avatar">{p.name[0]}</div><div className="grow"><b>{p.name}</b><small>Admisión: {p.admission}</small></div><button onClick={()=>{setSelected(p.id);setView('patient')}}>Ver expediente</button></div>)}{!data.patients.length&&<div className="empty">Aún no hay pacientes. Registra el primero.</div>}</section></>;
const Patient=()=> patient?<><header><div><button className="back" onClick={()=>setView('patients')}><ChevronLeft/>Pacientes</button><h1>{patient.name}</h1></div><div className="actions"><button onClick={()=>window.print()}><Printer/>Imprimir</button><button className="danger" onClick={()=>removePatient(patient.id)}><Trash2/>Eliminar</button></div></header><section className="panel"><h2>Datos básicos</h2><div className="fields four">{[['DNI','dni'],['Teléfono','phone'],['Email','email'],['Fecha de admisión','admission']].map(([l,k])=><label key={k}>{l}<input type={k==='admission'?'date':'text'} value={patient[k]||''} onChange={e=>updatePatient(k,e.target.value)}/></label>)}</div></section><section className="panel"><h2>Expediente clínico</h2><div className="docs">{docList.map(([id,n])=><button className="doc" key={id} onClick={()=>{setForm(id);setView('form')}}><FileText/><div><b>{n}</b><small>{(data.records[selected]||{})[id]?<><CheckCircle2/> Guardado</>:'Completar formulario'}</small></div><span>›</span></button>)}</div></section></>:null;
const Form=()=>{const f=forms[form];return <><header><div><button className="back" onClick={()=>setView('patient')}><ChevronLeft/>Expediente</button><p>{patient?.name}</p><h1>{f.title}</h1></div><button onClick={()=>window.print()}><Printer/>Imprimir</button></header><section className="panel form"><div className="notice"><Save/> Los cambios se guardan automáticamente en este navegador.</div>{f.sections.map(([title,fields],si)=><div className="formsection" key={si}><h2>{title}</h2>{fields.map((label,i)=>{const key=`${si}-${i}`;return <label key={key}>{label}<textarea rows={label.length>45?4:2} value={record[key]||''} onChange={e=>saveField(key,e.target.value)} placeholder="Escribe aquí…"/></label>})}</div>)}<div className="updated">Última actualización: {record._updated?new Date(record._updated).toLocaleString('es-PE'):'Sin guardar'}</div></section></>};
const Agenda=()=> <><header><div><p>Organización</p><h1>Agenda</h1></div></header><section className="panel"><h2>Próximas sesiones</h2><p className="muted">Módulo preparado para integrar calendario y recordatorios. En esta versión los expedientes y formularios ya funcionan localmente.</p></section></>;
return <div className="app"><Side/><main>{view==='dashboard'&&<Dashboard/>}{view==='patients'&&<Patients/>}{view==='patient'&&<Patient/>}{view==='form'&&<Form/>}{view==='agenda'&&<Agenda/>}{view==='documents'&&<><header><h1>Documentos clínicos</h1></header><section className="panel"><div className="docs">{docList.map(([id,n])=><div className="doc static" key={id}><FileText/><div><b>{n}</b><small>Disponible dentro del expediente de cada paciente</small></div></div>)}</div></section></>}{view==='risk'&&<><header><h1>Riesgo y seguridad</h1></header><section className="panel warning"><ShieldAlert/><div><h2>Módulos clínicos sensibles</h2><p>Evaluación inicial de riesgo y plan de seguridad están separados del resto del expediente para facilitar su acceso clínico.</p></div></section></>}</main></div>}
createRoot(document.getElementById('root')).render(<App/>);
